// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"MobileScreenScale","status":true,"description":"手機畫面縮放測試","parameters":{}},
{"name":"EnemyHpBar_MZ","status":true,"description":"v1.0.0 戰鬥怪物HP血條，顯示於敵人上方","parameters":{"Bar Width":"140","Bar Height":"14","Bar Y Offset":"-20","Show Name":"true","Show HP Text":"false","Name Font Size":"20","HP Font Size":"16","HP Color":"#FFFFFF","Bar Background":"#333333","Bar Color":"#E53935","Border Color":"#000000","Opacity":"255","Show Dead":"false"}},
{"name":"MiniMap_MZ","status":true,"description":"","parameters":{"Map Width":"300","Map Height":"200","Map Margin":"20","Map Top":"120","Border Width":"3","Background Opacity":"220","Player Size":"8","Event Size":"6","Update Rate":"10","MiniMap Start Switch":"20","Right Margin":"20","Show Events":"true","Show Player":"true","Hidden Map IDs":"0"}},
{"name":"UI_MapQuestLayout_Fix","status":false,"description":"v1.0 修正任務追蹤與小地圖位置重疊、遊戲視窗縮放後位置沒有更新","parameters":{}},
{"name":"VirtualJoystick_MZ","status":true,"description":"v1.0.0 手機虛擬搖桿：支援觸控移動、鍵盤操作與自動適應畫面","parameters":{"Enabled":"true","Joystick Size":"140","Knob Size":"58","Left Margin":"25","Bottom Margin":"30","Opacity":"150","Dead Zone":"15","Direction Threshold":"25","Move Interval":"5","Show On Desktop":"true","Hide During Events":"true","Hide During Menu":"true","Background Color":"rgba(80,80,80,0.65)","Knob Color":"rgba(220,220,220,0.85)"}},
{"name":"GetItemSound_MZ","status":true,"description":"獲得／扣除物品自動音效：普通／武器／防具／稀有／任務，共10種","parameters":{"Normal Get SE":"Item3","Normal Lose SE":"Cancel2","Weapon Get SE":"Equip1","Weapon Lose SE":"Cancel2","Armor Get SE":"Equip2","Armor Lose SE":"Cancel2","Rare Get SE":"Item1","Rare Lose SE":"Cancel2","Quest Get SE":"Decision2","Quest Lose SE":"Cancel2","Volume":"90","Pitch":"100","Pan":"0"}},
{"name":"QuestSystem_MZ_Core","status":true,"description":"v1.4.1 任務系統核心：任務資料、開始、進度、完成、追蹤、開關","parameters":{"Max Track":"1","Complete SE":"Applause1\r\n\r\n============================================================================"}},
{"name":"QuestSystem_MZ_Progress","status":true,"description":"v1.4.1 任務進度：所有取得物品自動同步、戰鬥擊殺自動同步","parameters":{}},
{"name":"QuestSystem_MZ_UI","status":true,"description":"v1.4.1 任務系統 UI：任務列表、詳細資料、任務追蹤、提示視窗","parameters":{}}
];
